### PR TITLE
feat: add CommandLine to more data tables

### PR DESCRIPTION
**Pull request by rfackroyd**
Hey all,

I noticed that I was getting errors for Sigma rules that used `CommandLine` in `file_event`, `registry_event`, `image_load`, and `network_connection` categories 

Therefore I am proposing we add the `InitiatingProcessCommandLine` field for the following tables:

- DeviceRegistryEvents
- DeviceNetworkEvents
- DeviceFileEvents
- DeviceImageLoadEvents

### CODE REVIEW

**Comment by slincoln-aiq** [comment]
Thanks for catching this! I can confirm that this is indeed an issue. However, I've implemented a different fix, as I attempted to account for this already with the `generic_field_mappings_proc_item` ProcessingItem, but was using a rule_condition rather than a field_name_condition to see if ProcessingItems have been applied or not.

The intended use for the ProcessingItem was to use a generic field mapping after all other category specific field mappings have been applied (or not) to fields, so fields that are not specified in each individual category mapping (but are present in nearly all M365 tables according to their table schema) can be mapped to a Sysmon field. This way, we don't have to list out every single field common to all tables in every single category specific field mapping; we can just fallback to the generic field mappings for common fields.  The CommandLine field that you mentioned is an example of this, and actually a special case as it's mapped to `ProcessCommandLine` in the DeviceProcessEvents table, but `InitiatingProcessCommandLine` in every other table, as seen in the DeviceProcessEvents specific field mapping and generic field mapping.

I've fixed this in the `dev` branch by using the correct condition in the `generic_field_mappings_proc_item`, and added a test to ensure it works correctly. Therefore, I won't merge this PR, but greatly appreciate the suggested fixes and looking into the issue. Once you have confirmed that #1 doesn't need any other fixes, I can merge dev to main and trigger a new release.

Thanks again!

**Comment by rfackroyd** [comment]
Nice, that certainly sounds like the clean approach to have the `generic_field_mappings_proc_item` as the fallback. I was looking at it from the approach that the legacy `mdatp.py` backend used which did list all fields for each table - which infringes on Don't-Repeat-Yourself, technically. So this is an improvement!

**Comment by rfackroyd** [comment]
@slincoln-aiq Was meant to mention on this topic - I noticed `generic_field_mappings` there was no `ParentImage` to `InitiatingProcessParentFileName` - I am assuming this was left our because Microsoft (frustratingly) don't provide a field called `InitiatingProcessParentFolderPath`?

As most Sigma users will be dropping in directory path segments in `ParentImage`, it wouldn't match on the 'FileName' field.

**Comment by slincoln-aiq** [comment]
Yep, that's correct - they have the `InitiatingProcessParentFileName` field, but not `InitiatingProcessParentFolderPath`.  Since Image & ParentImage is the whole path including the folder and file, the query would not be correct if we set `ParentImage` to `InitiatingProcessParentFileName`.  

However, I suppose what we could do instead is just grab the parent process name from ParentImage and set it to `InitiatingProcessParentFileName` with a transformation and field name condition for `ParentImage`.  We would have to make it very explicit to the user that it's not taking into consideration the whole path and just the process name since the table schema doesn't support the whole path, just in case users think their detection(s) are matching the whole path.

**Comment by rfackroyd** [comment]
I think that's a good idea. In the case where ParentImage does not match a process name, it's dropped, and where it does you can snip out `<process>.exe` with an expression. You are correct as this may broaden the scope of their detection as you reduce the specificity of the path, and therefore warrant a warning. That being said, I think a large portion of Sigma rules will simply be process names on their own anyway, and therefore this feature will be useful to users.

**Pull request closed without merging**
